# DEVELOPMENT DOCKERFILE
# This Dockerfile is used for development with hot reloading
# For production, use the main Dockerfile instead
# Key differences:
# - Uses Node.js directly instead of Nginx
# - Doesn't copy source files (mounted as volume)
# - Runs React dev server instead of serving static files

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# We don't need to copy the source code as it will be mounted as a volume
# This allows for hot reloading during development

EXPOSE 3000

CMD ["npm", "start"] 