version: '3.8'

# DEVELOPMENT CONFIGURATION
# For production, use docker-compose.prod.yml instead
# Key differences in dev:
# - Uses Dockerfile.dev for frontend
# - Mounts volumes for hot reloading
# - Uses port 3000 for React dev server
services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: mellow_db
      POSTGRES_USER: mellow_user
      POSTGRES_PASSWORD: mellow_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - mellow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mellow_user -d mellow_db"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - node-backend
    networks:
      - mellow-network
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_IN_DOCKER=true
    restart: unless-stopped

  node-backend:
    build:
      context: ./backend/node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      python-ai:
        condition: service_started
    environment:
      - PYTHON_AI_URL=http://python-ai:8000
      - DB_TYPE=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mellow_db
      - DB_USER=mellow_user
      - DB_PASSWORD=mellow_password
    networks:
      - mellow-network
    restart: unless-stopped

  python-ai:
    build:
      context: ./backend/python-ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mellow_db
      - DB_USER=mellow_user
      - DB_PASSWORD=mellow_password
    networks:
      - mellow-network
    restart: unless-stopped

networks:
  mellow-network:
    driver: bridge

volumes:
  postgres-data: 