version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - node-backend
    restart: unless-stopped

  node-backend:
    build:
      context: ./backend/node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - node-db-data:/app/data
    depends_on:
      - python-ai
    environment:
      - PYTHON_AI_URL=http://python-ai:8000
      - DB_PATH=/app/data/chat.db
    restart: unless-stopped

  python-ai:
    build:
      context: ./backend/python-ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  node-db-data: 